In [3]:
# importing required packages
# data operation libraries

import numpy as np
import pandas as pd
# visualization libraries

import matplotlib.pyplot as plt
import seaborn as sns
# For regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [4]:
dataset = pd.read_csv(r'dataset/Advertising.csv')

dataset

     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [5]:
## Prepare the independent dataset
Data = dataset.drop(['Unnamed: 0'], axis=1)
Data

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [6]:
## Identify X & Y that is independant and dependant variable directly
X = Data[['TV', 'Radio', 'Newspaper']]
y = dataset.Sales

In [7]:
## Split between train and test 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)

# 1. Subset Selection

# Forward Selection

In [8]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

forward = SequentialFeatureSelector(
    lr,
    n_features_to_select=2,
    direction='forward'
)

forward.fit(X, y)
selected_forward = X.columns[forward.get_support()]
print("Forward Selection:", selected_forward.tolist())

Forward Selection: ['TV', 'Radio']

# Backward Selection

In [9]:
backward = SequentialFeatureSelector(
    lr,
    n_features_to_select=2,
    direction='backward'
)

backward.fit(X, y)
selected_backward = X.columns[backward.get_support()]
print("Backward Selection:", selected_backward.tolist())

Backward Selection: ['TV', 'Radio']

# Regularization

# -----------------------------------------------------
# 3. Ridge Regression
# -----------------------------------------------------

In [10]:
#creating a ridge regression object from scikit learn
ridge = Ridge(alpha=120.0) #alpha is regularization strength (λ).
ridge.fit(X_train, y_train)

ridge_pred = ridge.predict(X_test)
ridge_mse = mean_squared_error(y_test, ridge_pred)

print("=== Ridge Regression ===")
print("Coefficients:", ridge.coef_)
print("Intercept:", ridge.intercept_)
print("MSE:", ridge_mse)
print()

=== Ridge Regression ===
Coefficients: [0.04694806 0.17580726 0.00207333]
Intercept: 2.9491922536164434
MSE: 1.9404777394564063

# -----------------------------------------------------
# 4. Lasso Regression
# -----------------------------------------------------

In [11]:
# create an object of Lasso Regression model with regularization strength alpha = 0.1.
lasso = Lasso(alpha=0.01)
lasso.fit(X_train, y_train)

lasso_pred = lasso.predict(X_test)
lasso_mse = mean_squared_error(y_test, lasso_pred)

print("=== Lasso Regression ===")
print("Coefficients:", lasso.coef_)
print("Intercept:", lasso.intercept_)
print("MSE:", lasso_mse)

=== Lasso Regression ===
Coefficients: [0.04695111 0.17655104 0.00184   ]
Intercept: 2.938505621130574
MSE: 1.929387097542705

# Using credit card example

In [12]:
#importing all the required packages
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [13]:
# Example: Credit.csv (ISLR)
df_credit = pd.read_csv(r"dataset/Credit.csv")
df_credit

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
2,104.593,7075,514,4,71,11,No,No,No,West,580
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
4,55.882,4897,357,2,68,16,No,No,Yes,South,331
...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560
396,13.364,3838,296,5,65,17,No,No,No,East,480
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138
398,37.728,2525,192,1,44,13,No,No,Yes,South,0
399,18.701,5524,415,5,64,7,Yes,No,No,West,966

In [14]:
df_credit.dtypes

Income       float64
Limit          int64
Rating         int64
Cards          int64
Age            int64
Education      int64
Own              str
Student          str
Married          str
Region           str
Balance        int64
dtype: object

In [15]:
df_credit.corr()

ValueError: could not convert string to float: 'No'

In [16]:
## Check for correlation and draw the heat-map
corr = df_credit.corr()
sns.heatmap(corr, vmax=1, vmin=-1, annot=True, cmap='GnBu')

ValueError: could not convert string to float: 'No'

In [ ]:
X = df_credit[['Income','Limit','Rating','Cards','Age','Education']]
y = df_credit['Balance']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# ordinary linear regression

lr = LinearRegression().fit(X_train, y_train)
print("Linear RMSE:", mean_squared_error(y_test, lr.predict(X_test), squared=False))
print("Coefficients = ", lr.coef_)
print("Intercept = ", lr.intercept_)
print("\nRegression Coefficients:")
print(pd.Series(lr.coef_, index=X.columns))

In [ ]:
# Ridge regression
ridge = Ridge(alpha=10)
ridge.fit(X_train, y_train)
print("Ridge RMSE:", mean_squared_error(y_test, ridge.predict(X_test), squared=False))
print("Coefficients = ", ridge.coef_)
print("Intercept = ", ridge.intercept_)
print("\nRidge Coefficients:")
print(pd.Series(ridge.coef_, index=X.columns))

In [ ]:
# Lasso regression
lasso = Lasso(alpha=30.0)
lasso.fit(X_train, y_train)
print("Lasso RMSE:", mean_squared_error(y_test, lasso.predict(X_test), squared=False))
print("Coefficients = ", lasso.coef_)
print("Intercept = ", lasso.intercept_)
print("\Lasso Coefficients:")
print(pd.Series(lasso.coef_, index=X.columns))

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Sample data
data = {'Own': ['Yes', 'No', 'Yes', 'No'],
        'Student': ['No', 'Yes', 'Yes', 'No']}

import pandas as pd
df = pd.DataFrame(data)

# Initialize encoder
le = LabelEncoder()

# Apply to each column
df['Own_encoded'] = le.fit_transform(df['Own'])
df['Student_encoded'] = le.fit_transform(df['Student'])

print(df)

In [ ]:
from sklearn.linear_model import LassoCV, RidgeCV

lasso_cv = LassoCV(cv=10).fit(X_train, y_train)
ridge_cv = RidgeCV(alphas=[0.1,1,10,100,200]).fit(X_train, y_train)

print(lasso_cv.alpha_)
print(ridge_cv.alpha_)

In [ ]:
df5 = df_credit
df5

In [ ]:

# Initialize encoder
le = LabelEncoder()

# Apply to each column
df5['Own_encoded'] = le.fit_transform(df5['Own'])
df5['Student_encoded'] = le.fit_transform(df5['Student'])

print(df5)

In [ ]:
df6 = df_credit

In [ ]:
df_encoded = pd.get_dummies(df6, columns=['Own', 'Student', 'Married', 'Region'], drop_first=True)
df_encoded